App/TranslationAssistant.Web/Controllers/LineController.cs
#region Using statements

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using AutoMapper;
using Microsoft.AspNet.Identity;
using TranslationAssistant.Contracts.Managers;
using TranslationAssistant.Core;
using TranslationAssistant.Web.Core.Models.Lines;

#endregion

namespace TranslationAssistant.Web.Controllers
{
    [Authorize]
    public class LineController : Controller
    {
        private readonly ILineManager _manager;

        public LineController(ILineManager manager)
        {
            _manager = manager;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var userGuid = Guid.Parse(User.Identity.GetUserId());

            var lines = _manager.GetLinesByUserId(userGuid);
            var lineViewModels = Mapper.Map<IQueryable<Line>, List<LineViewModel>>(lines);

            return View(lineViewModels);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return PartialView("_CreateLine");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LineViewModel model)
        {
            if (ModelState.IsValid)
            {
                var line = Mapper.Map<LineViewModel, Line>(model);
                _manager.Add(line);
            }

            if (HttpContext.Request.UrlReferrer != null)
                return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var line = _manager.GetLineById(id);
            var lineViewModel = Mapper.Map<Line, LineViewModel>(line);

            return View(lineViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, LineViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var line = _manager.GetLineById(id);
            line = Mapper.Map<LineViewModel, Line>(model, line);
            
            _manager.Update(line);

            return RedirectToAction("Edit", "Project", new RouteValueDictionary {{"id", model.ProjectId}});
        }

        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            _manager.Remove(id);

            if (HttpContext.Request.UrlReferrer != null)
                return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);

            return RedirectToAction("Index");
        }
    }
}

App/TranslationAssistant.Web/Controllers/ProjectController.cs
#region Using statements

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using TranslationAssistant.Contracts.Managers;
using TranslationAssistant.Core;
using TranslationAssistant.Web.Core.Models.Projects;

#endregion

namespace TranslationAssistant.Web.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly IProjectManager _manager;

        public ProjectController(IProjectManager manager)
        {
            _manager = manager;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var userGuid = Guid.Parse(User.Identity.GetUserId());

            var projects = _manager.GetProjectsByUserId(userGuid);
            var projectViewModels = Mapper.Map<IQueryable<Project>, List<ProjectViewModel>>(projects);

            return View(projectViewModels);
        }

        [HttpGet]
        public ActionResult Details(Guid id)
        {
            var project = _manager.GetProjectById(id);
            var projectLineViewModel = Mapper.Map<Project, ProjectLineViewModel>(project);

            return View(projectLineViewModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProjectViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var project = Mapper.Map<ProjectViewModel, Project>(model);
            project.UserId = Guid.Parse(User.Identity.GetUserId());

            _manager.Add(project);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var project = _manager.GetProjectById(id);
            var projectLineViewModel = Mapper.Map<Project, ProjectLineViewModel>(project);

            return View(projectLineViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, ProjectLineViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var project = _manager.GetProjectById(id);
            project = Mapper.Map<ProjectViewModel, Project>(model, project);

            _manager.Update(project);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            _manager.Remove(id);

            return RedirectToAction("Index");
        }
    }
}

App/TranslationAssistant.Web/Views/Project/Create.cshtml
@model TranslationAssistant.Web.Core.Models.Projects.ProjectViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProjectViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

App/TranslationAssistant.Web/Views/Project/Details.cshtml
@using GridMvc.Html

@model TranslationAssistant.Web.Core.Models.Projects.ProjectLineViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProjectViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

    </dl>
</div>

@Html.Grid(Model.Lines).Columns(columns =>
{
    columns.Add(l => l.Word)
        .Titled("Word");

    columns.Add(l => l.Description)
        .Titled("Word's description");
    
}).WithPaging(10)

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

App/TranslationAssistant.Web/Views/Project/Edit.cshtml
@using GridMvc.Html
@using TranslationAssistant.Web.Core.Models.Projects
@using TranslationAssistant.Web.Core.Models.Lines


@model ProjectLineViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProjectViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div> 
    </div>
}

@Html.Partial("_CreateLine", new LineViewModel{ ProjectId = Model.Id })


@Html.Grid(Model.Lines).Columns(columns =>
{
    columns.Add(l => l.Word)
        .Titled("Word");

    columns.Add(l => l.Description)
        .Titled("Word's description");

    columns.Add(l => l.Id)
        .Titled("")
        .SetWidth(150)
        .Sanitized(false)
        .Encoded(false)
        .RenderValueAs(l =>
            @<b>
                @Html.ActionLink("Edit", "Edit", "Line", new { id = l.Id },
                     new { @class = " btn btn-warning" })

                @Html.ActionLink("Delete", "Delete", "Line" , new { id = l.Id },
                     new { @class = "btn btn-danger" })
            </b>);

}).WithPaging(5)


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/rollupper")
}

App/TranslationAssistant.Web/Views/Project/Index.cshtml
@model IEnumerable<TranslationAssistant.Web.Core.Models.Projects.ProjectViewModel>

@using GridMvc.Html

@{
    ViewBag.Title = "Index";
}

<h2>Your Projects</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { }, new { @class = "btn btn-success" })
</p>

@Html.Grid(Model).Columns(columns =>
{
    columns.Add(p => p.Title)
        .Titled("Title");

    columns.Add(p => p.CreateDate)
        .Titled("Create date");

    columns.Add(p => p.Id)
        .Titled("")
        .SetWidth(225)
        .Sanitized(false)
        .Encoded(false)
        .RenderValueAs(p =>
            @<b>
                 @Html.ActionLink("Edit", "Edit", new {id = p.Id},
                     new {@class = " btn btn-default"})

                 @Html.ActionLink("Details", "Details", new {id = p.Id},
                     new {@class = " btn btn-default"})
    
                 @Html.ActionLink("Delete", "Delete", new {id = p.Id},
                     new {@class = "btn btn-danger"})
             </b>);
}).WithPaging(5)